# Generated by Django 3.2.5 on 2021-07-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
